objects/AutoRabitTest__c.object
<CustomObject>
    <fields>
        <fullName>CP_Mail__c</fullName>
        <label>CP Mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CP_Phone__c</fullName>
        <label>CP Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CounterParty__c</fullName>
        <label>CounterParty</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <label>AutoRabitTest</label>
    <nameField>
        <label>AutoRabitTest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AutoRabitTest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AutoRabitTestClass.cls
public class AutoRabitTestClass{
    
    public Id posId{get;set;}
    public Id DealsId{get;set;}
     String test = Label.DX_API;

 
    Public AutoRabitTestClass(Apexpages.StandardController controller){
        posId = controller.getRecord().Id;
        System.debug('posid'+posId);
    }
    public List<AutoRabitTest__c > cs{get; set;}
    PageReference pr = new PageReference('/apex/AutoRabitTestPage1');
    public AutoRabitTestClass()
    {
    cs = new List<AutoRabitTest__c >();
        List<AutoRabitTest__c > a= [Select id,CounterParty__c,CP_Mail__c , CP_Phone__c from AutoRabitTest__c where id=:posId  ];
       for (AutoRabitTest__c  c : a)
       {       
           cs.add(c);
       }
    }
   
    
}